[workspace]
members = [
  "api",
  "atom_generator",
  "definition_fetcher",
  "ffi",
]
resolver = "2"

[patch."agrian-registry".ffi_common]
# path = "../ffi_common/ffi_common"
git = "ssh://git@github.com/agrian-inc/ffi_common.git"
branch = "develop"

[patch."agrian-registry".ffi_consumer]
# path = "../ffi_common/ffi_consumer"
git = "ssh://git@github.com/agrian-inc/ffi_common.git"
branch = "develop"

[patch."agrian-registry".ffi_derive]
# path = "../ffi_common/ffi_derive"
git = "ssh://git@github.com/agrian-inc/ffi_common.git"
branch = "develop"

[patch."agrian-registry".ffi_internals]
# path = "../ffi_common/ffi_derive"
git = "ssh://git@github.com/agrian-inc/ffi_common.git"
branch = "develop"
