//-----------------------------------------------------------------------------
// DO NOT EDIT THIS FILE!
// This is generated at compile time.
//-----------------------------------------------------------------------------

pub(super) mod symbol_parser {
    #[derive(Parser)]
    #[grammar = "/Users/sloveless/Development/agrian/wise_units/parser/symbol.pest"]
    pub struct SymbolParser;
}
