[package]
name = "wise_units"
version = "0.17.1"
description = "Measure things using UCUM units"
repository = "https://github.com/agrian-inc/wise_units"
license = "MIT"
authors = ["Steve Loveless <steve@agrian.com>"]
edition = "2018"
publish = ["agrian-registry"]

[dependencies]
approx = "0.5"
ffi_common = { version = "0.3", registry = "agrian-registry", optional = true }
ffi_derive = { version = "0.3", registry = "agrian-registry", optional = true }
log = "0.4"
paste = { version = "1.0", optional = true }
pest = "^2.0"
pest_derive = "^2.0"
serde = { version = "1.0", optional = true, features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.1"
criterion = "0.3"
lazy_static = "1.4"
pretty_env_logger = "0.4"
rmp-serde = "0.15"
serde_json = "1.0"

[features]
# Enables the C foreign function interface. Some types may become repr(C) under this flag, and an
# additional ffi module will be generated for each supported resource type.
cffi = ["ffi_derive", "paste", "ffi_common"]

[[bench]]
name = "measurements_benchmarks"
harness = false

[[bench]]
name = "unit_benchmarks"
harness = false
